#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sodexo.Android.Resource", IsApplication=true)]

namespace Sodexo.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::Sodexo.Android.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int Anim_Fade_In = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Anim_Fade_Out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Slide_In_Left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Slide_In_Right = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Slide_Out_Left = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Slide_Out_Right = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accounts_btn_next = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int accounts_cell_info_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int accounts_cell_separate_line = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int accounts_header_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int addoffer_bg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_delete = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_edit = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_info = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dashboard_header_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int edittext_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int feedback_header_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_add = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_back = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_basic = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_bottom_arrow = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_delete = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_female = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon_filter = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int icon_info = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int icon_lock = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int icon_m = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int icon_menu = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icon_plus = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int icon_right_arrow = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int icon_search = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int img_active = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int img_add = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int img_cold_beverage_dispensed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int img_inactive = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int img_logout = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int img_offer_categories_1 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int img_offer_categories_2 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int img_offer_categories_3 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int img_offer_categories_4 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int img_offer_categories_5 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int img_offer_categories_6 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int img_profile = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int indicator_accountsetup = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int indicator_generalinfo = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int indicator_planogram = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int indicator_promotion = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int indicator_surveyorfeedback = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int indicator_usersetup = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int info_btn_green = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int line_dots = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int line_solid_light_gray = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int logo = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int logo_itz = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int logo_sodexo = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int me_header_bg = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int menu_accounts_off = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int menu_accounts_on = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int menu_dashboard_off = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int menu_dashboard_on = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int menu_feedback_off = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int menu_feedback_on = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int menu_logo_off = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int menu_logo_on = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int menu_me_off = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int menu_me_on = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int menu_prices_off = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int menu_prices_on = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int menu_promotions_off = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int menu_promotions_on = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int outlet_default = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int prices_header_bg = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int progress_empty = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int progress_full = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int progress_text_bg = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int promotion_all = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int promotion_cell_separator = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int promotion_cold_beverage = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int promotion_cold_beverage_dispensed = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int promotion_cold_beverage_impulse = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int promotion_cold_beverage_main_vault = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int promotion_hot_beverages = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int promotion_in_my_kitchen = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int promotion_mindful = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int promotion_mutualized = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int promotion_pricing = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int promotion_simply_to_go = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int promotions_header_bg = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int radiobtn_empty = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int radiobtn_full = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int spinner_bg = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int splash_bg = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int star_empty = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int star_full = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int symbol_accountsetup = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int symbol_generalinfo = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int symbol_planogram = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int symbol_promotion = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int symbol_surveyorfeedback = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int symbol_usersetup = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int temp_offer = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int temp_offer_added = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int temp_planogram = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int text_no_planogram = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int text_with_planogram = 2130837604;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int accountdetail_account_ll = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int accountdetail_address_tv = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int accountdetail_edit_btn = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int accountdetail_listview = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int accountdetail_locationid_tv = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int accountdetail_name_tv = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int accounts_cell_address_tv = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int accounts_cell_arrow_iv = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int accounts_cell_contents_ll = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int accounts_cell_locationid_tv = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int accounts_cell_name_tv = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int accounts_cell_navigate_btn = 2131099667;
			
			// aapt resource value: 0x7f06000d
			public const int accounts_cell_number_tv = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int accounts_cell_plus_iv = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int accounts_cell_separate_line_iv = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int accounts_listview = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int accountview_address_tv = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int accountview_edit_btn = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int accountview_locationid_tv = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int accountview_name_tv = 2131099648;
			
			// aapt resource value: 0x7f060019
			public const int addoutlet_add_fl = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int addoutlet_addnew_btn = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int addoutlet_addphoto_imgbtn = 2131099677;
			
			// aapt resource value: 0x7f060018
			public const int addoutlet_bottom_ll = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int addoutlet_header_fl = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int addoutlet_ll = 2131099669;
			
			// aapt resource value: 0x7f06001e
			public const int addoutlet_next_btn = 2131099678;
			
			// aapt resource value: 0x7f06001a
			public const int addoutlet_number_tv = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int addoutlet_photos_fl = 2131099676;
			
			// aapt resource value: 0x7f060014
			public const int addoutlet_sv = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int addoutlet_views_ll = 2131099671;
			
			// aapt resource value: 0x7f060026
			public const int addoutletview_annualsales_info_imgbtn = 2131099686;
			
			// aapt resource value: 0x7f060025
			public const int addoutletview_annualsales_sp = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int addoutletview_consumer_info_imgbtn = 2131099684;
			
			// aapt resource value: 0x7f060023
			public const int addoutletview_consumer_sp = 2131099683;
			
			// aapt resource value: 0x7f060020
			public const int addoutletview_delete_account_fl = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int addoutletview_delete_outlet_btn = 2131099681;
			
			// aapt resource value: 0x7f060027
			public const int addoutletview_localcompetition_sp = 2131099687;
			
			// aapt resource value: 0x7f060022
			public const int addoutletview_name_et = 2131099682;
			
			// aapt resource value: 0x7f06001f
			public const int addoutletview_number_tv = 2131099679;
			
			// aapt resource value: 0x7f06002e
			public const int dashboard_cell_date_tv = 2131099694;
			
			// aapt resource value: 0x7f060035
			public const int dashboard_cell_desc_tv = 2131099701;
			
			// aapt resource value: 0x7f06002b
			public const int dashboard_cell_indicator_iv = 2131099691;
			
			// aapt resource value: 0x7f06002f
			public const int dashboard_cell_picture_iv = 2131099695;
			
			// aapt resource value: 0x7f060031
			public const int dashboard_cell_progress_empty_iv = 2131099697;
			
			// aapt resource value: 0x7f060030
			public const int dashboard_cell_progress_fl = 2131099696;
			
			// aapt resource value: 0x7f060032
			public const int dashboard_cell_progress_full_ll = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int dashboard_cell_progress_value_fl = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int dashboard_cell_progress_value_tv = 2131099700;
			
			// aapt resource value: 0x7f06002c
			public const int dashboard_cell_symbol_iv = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int dashboard_cell_title_tv = 2131099693;
			
			// aapt resource value: 0x7f06002a
			public const int dashboard_cell_top_fl = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int dashboard_cell_view = 2131099689;
			
			// aapt resource value: 0x7f060028
			public const int dashboard_listview = 2131099688;
			
			// aapt resource value: 0x7f06003a
			public const int decision_answers_ll = 2131099706;
			
			// aapt resource value: 0x7f060039
			public const int decision_question_tv = 2131099705;
			
			// aapt resource value: 0x7f06003d
			public const int feedback_apprelated_iv = 2131099709;
			
			// aapt resource value: 0x7f060040
			public const int feedback_kitchen_iv = 2131099712;
			
			// aapt resource value: 0x7f06003f
			public const int feedback_mindful_iv = 2131099711;
			
			// aapt resource value: 0x7f06003b
			public const int feedback_planogram_iv = 2131099707;
			
			// aapt resource value: 0x7f06003e
			public const int feedback_pricing_iv = 2131099710;
			
			// aapt resource value: 0x7f06003c
			public const int feedback_promotions_iv = 2131099708;
			
			// aapt resource value: 0x7f060041
			public const int fullimage_webview = 2131099713;
			
			// aapt resource value: 0x7f06005d
			public const int imageView1 = 2131099741;
			
			// aapt resource value: 0x7f060060
			public const int imageView2 = 2131099744;
			
			// aapt resource value: 0x7f060063
			public const int imageView3 = 2131099747;
			
			// aapt resource value: 0x7f060056
			public const int leavefeedback_attach_btn = 2131099734;
			
			// aapt resource value: 0x7f060054
			public const int leavefeedback_comment_et = 2131099732;
			
			// aapt resource value: 0x7f060053
			public const int leavefeedback_comment_tv = 2131099731;
			
			// aapt resource value: 0x7f060050
			public const int leavefeedback_content_fl = 2131099728;
			
			// aapt resource value: 0x7f06004c
			public const int leavefeedback_offer_fl = 2131099724;
			
			// aapt resource value: 0x7f06004e
			public const int leavefeedback_offer_name_tv = 2131099726;
			
			// aapt resource value: 0x7f06004d
			public const int leavefeedback_offer_picture_iv = 2131099725;
			
			// aapt resource value: 0x7f06004f
			public const int leavefeedback_offer_status_tv = 2131099727;
			
			// aapt resource value: 0x7f060055
			public const int leavefeedback_picture_iv = 2131099733;
			
			// aapt resource value: 0x7f060047
			public const int leavefeedback_promotion_category_iv = 2131099719;
			
			// aapt resource value: 0x7f060049
			public const int leavefeedback_promotion_date_tv = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int leavefeedback_promotion_desc_tv = 2131099722;
			
			// aapt resource value: 0x7f060045
			public const int leavefeedback_promotion_ll = 2131099717;
			
			// aapt resource value: 0x7f060048
			public const int leavefeedback_promotion_name_tv = 2131099720;
			
			// aapt resource value: 0x7f060046
			public const int leavefeedback_promotion_picture_iv = 2131099718;
			
			// aapt resource value: 0x7f06004b
			public const int leavefeedback_promotion_status_iv = 2131099723;
			
			// aapt resource value: 0x7f060052
			public const int leavefeedback_question_tv = 2131099730;
			
			// aapt resource value: 0x7f060051
			public const int leavefeedback_rate_fl = 2131099729;
			
			// aapt resource value: 0x7f060057
			public const int leavefeedback_send_btn = 2131099735;
			
			// aapt resource value: 0x7f060042
			public const int leavefeedback_sv = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int leavefeedback_title_fl = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int leavefeedback_title_tv = 2131099716;
			
			// aapt resource value: 0x7f060059
			public const int lookpaccount_ll = 2131099737;
			
			// aapt resource value: 0x7f060067
			public const int lookupaccount_address1_tv = 2131099751;
			
			// aapt resource value: 0x7f060068
			public const int lookupaccount_address2_tv = 2131099752;
			
			// aapt resource value: 0x7f06006c
			public const int lookupaccount_business_segment_tv = 2131099756;
			
			// aapt resource value: 0x7f060069
			public const int lookupaccount_city_tv = 2131099753;
			
			// aapt resource value: 0x7f06006d
			public const int lookupaccount_consumer_type_sp = 2131099757;
			
			// aapt resource value: 0x7f060061
			public const int lookupaccount_delete_account_btn = 2131099745;
			
			// aapt resource value: 0x7f06005f
			public const int lookupaccount_delete_account_fl = 2131099743;
			
			// aapt resource value: 0x7f06005b
			public const int lookupaccount_desc_tv = 2131099739;
			
			// aapt resource value: 0x7f060064
			public const int lookupaccount_lookup_btn = 2131099748;
			
			// aapt resource value: 0x7f060062
			public const int lookupaccount_lookup_fl = 2131099746;
			
			// aapt resource value: 0x7f06006e
			public const int lookupaccount_next_btn = 2131099758;
			
			// aapt resource value: 0x7f06006a
			public const int lookupaccount_state_tv = 2131099754;
			
			// aapt resource value: 0x7f060058
			public const int lookupaccount_sv = 2131099736;
			
			// aapt resource value: 0x7f06005a
			public const int lookupaccount_title_tv = 2131099738;
			
			// aapt resource value: 0x7f060065
			public const int lookupaccount_unit_content_fl = 2131099749;
			
			// aapt resource value: 0x7f060066
			public const int lookupaccount_unit_name_tv = 2131099750;
			
			// aapt resource value: 0x7f06005e
			public const int lookupaccount_unit_number_et = 2131099742;
			
			// aapt resource value: 0x7f06005c
			public const int lookupaccount_unit_number_fl = 2131099740;
			
			// aapt resource value: 0x7f06006b
			public const int lookupaccount_zip_tv = 2131099755;
			
			// aapt resource value: 0x7f060079
			public const int main_content_fl = 2131099769;
			
			// aapt resource value: 0x7f060076
			public const int main_header_add_btn = 2131099766;
			
			// aapt resource value: 0x7f060073
			public const int main_header_back_btn = 2131099763;
			
			// aapt resource value: 0x7f060075
			public const int main_header_change_btn = 2131099765;
			
			// aapt resource value: 0x7f060077
			public const int main_header_filter_btn = 2131099767;
			
			// aapt resource value: 0x7f060070
			public const int main_header_fl = 2131099760;
			
			// aapt resource value: 0x7f060078
			public const int main_header_info_btn = 2131099768;
			
			// aapt resource value: 0x7f060071
			public const int main_header_iv = 2131099761;
			
			// aapt resource value: 0x7f060072
			public const int main_header_menu_btn = 2131099762;
			
			// aapt resource value: 0x7f060074
			public const int main_header_title_tv = 2131099764;
			
			// aapt resource value: 0x7f06007c
			public const int main_menu_accounts_btn = 2131099772;
			
			// aapt resource value: 0x7f06007b
			public const int main_menu_dashboard_btn = 2131099771;
			
			// aapt resource value: 0x7f06007e
			public const int main_menu_feedback_btn = 2131099774;
			
			// aapt resource value: 0x7f06007a
			public const int main_menu_ll = 2131099770;
			
			// aapt resource value: 0x7f060081
			public const int main_menu_logo_btn = 2131099777;
			
			// aapt resource value: 0x7f060080
			public const int main_menu_me_btn = 2131099776;
			
			// aapt resource value: 0x7f06007f
			public const int main_menu_prices_btn = 2131099775;
			
			// aapt resource value: 0x7f06007d
			public const int main_menu_promotions_btn = 2131099773;
			
			// aapt resource value: 0x7f06006f
			public const int main_view = 2131099759;
			
			// aapt resource value: 0x7f060082
			public const int me_avatar_iv = 2131099778;
			
			// aapt resource value: 0x7f060086
			public const int me_logout_btn = 2131099782;
			
			// aapt resource value: 0x7f060083
			public const int me_name_tv = 2131099779;
			
			// aapt resource value: 0x7f060084
			public const int me_title_tv = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int me_upload_btn = 2131099781;
			
			// aapt resource value: 0x7f06008d
			public const int offercategoryview_btn = 2131099789;
			
			// aapt resource value: 0x7f06008c
			public const int offercategoryview_name_tv = 2131099788;
			
			// aapt resource value: 0x7f06008b
			public const int offercategoryview_picture_iv = 2131099787;
			
			// aapt resource value: 0x7f060093
			public const int offerdetail_content_ll = 2131099795;
			
			// aapt resource value: 0x7f060092
			public const int offerdetail_offer_edit_imgbtn = 2131099794;
			
			// aapt resource value: 0x7f060090
			public const int offerdetail_offer_name_tv = 2131099792;
			
			// aapt resource value: 0x7f06008f
			public const int offerdetail_offer_picture_iv = 2131099791;
			
			// aapt resource value: 0x7f060091
			public const int offerdetail_offer_status_tv = 2131099793;
			
			// aapt resource value: 0x7f06009b
			public const int offerdetail_photos_fl = 2131099803;
			
			// aapt resource value: 0x7f06009c
			public const int offerdetail_photosview_add_imgbtn = 2131099804;
			
			// aapt resource value: 0x7f06009d
			public const int offerdetail_photosview_addphoto_tv = 2131099805;
			
			// aapt resource value: 0x7f060095
			public const int offerdetail_planogram_detail_tv = 2131099797;
			
			// aapt resource value: 0x7f060094
			public const int offerdetail_planogram_picture_iv = 2131099796;
			
			// aapt resource value: 0x7f06009a
			public const int offerdetail_planogram_status_iv = 2131099802;
			
			// aapt resource value: 0x7f060099
			public const int offerdetail_planogram_status_tv = 2131099801;
			
			// aapt resource value: 0x7f060097
			public const int offerdetail_sendfeedback_btn = 2131099799;
			
			// aapt resource value: 0x7f060098
			public const int offerdetail_sendtomail_btn = 2131099800;
			
			// aapt resource value: 0x7f06008e
			public const int offerdetail_sv = 2131099790;
			
			// aapt resource value: 0x7f060096
			public const int offerdetail_viewpog_btn = 2131099798;
			
			// aapt resource value: 0x7f060088
			public const int offerview_name_tv = 2131099784;
			
			// aapt resource value: 0x7f06008a
			public const int offerview_navigate_btn = 2131099786;
			
			// aapt resource value: 0x7f060087
			public const int offerview_picture_iv = 2131099783;
			
			// aapt resource value: 0x7f060089
			public const int offerview_status_tv = 2131099785;
			
			// aapt resource value: 0x7f06009f
			public const int outlet_view_name_tv = 2131099807;
			
			// aapt resource value: 0x7f06009e
			public const int outlet_view_picture_iv = 2131099806;
			
			// aapt resource value: 0x7f0600a5
			public const int outletdetail_addnew_btn = 2131099813;
			
			// aapt resource value: 0x7f0600a4
			public const int outletdetail_addnew_fl = 2131099812;
			
			// aapt resource value: 0x7f0600a8
			public const int outletdetail_addoffer_btn = 2131099816;
			
			// aapt resource value: 0x7f0600a9
			public const int outletdetail_cancel_btn = 2131099817;
			
			// aapt resource value: 0x7f0600a2
			public const int outletdetail_edit_imgbtn = 2131099810;
			
			// aapt resource value: 0x7f0600a1
			public const int outletdetail_name_tv = 2131099809;
			
			// aapt resource value: 0x7f0600a7
			public const int outletdetail_offercategories_fl = 2131099815;
			
			// aapt resource value: 0x7f0600a6
			public const int outletdetail_offercategories_ll = 2131099814;
			
			// aapt resource value: 0x7f0600a3
			public const int outletdetail_offers_ll = 2131099811;
			
			// aapt resource value: 0x7f0600a0
			public const int outletdetail_picture_iv = 2131099808;
			
			// aapt resource value: 0x7f0600ac
			public const int planogramcell_offers_ll = 2131099820;
			
			// aapt resource value: 0x7f0600ab
			public const int planogramcell_outlet_name_tv = 2131099819;
			
			// aapt resource value: 0x7f0600aa
			public const int planogramcell_outlet_picture_iv = 2131099818;
			
			// aapt resource value: 0x7f0600ad
			public const int planograms_listview = 2131099821;
			
			// aapt resource value: 0x7f0600b0
			public const int prices_advanced_ll = 2131099824;
			
			// aapt resource value: 0x7f0600b8
			public const int prices_basic_keyword_et = 2131099832;
			
			// aapt resource value: 0x7f0600b7
			public const int prices_basic_ll = 2131099831;
			
			// aapt resource value: 0x7f0600b3
			public const int prices_business_segment_sp = 2131099827;
			
			// aapt resource value: 0x7f0600b4
			public const int prices_consumer_type_sp = 2131099828;
			
			// aapt resource value: 0x7f0600af
			public const int prices_container_ll = 2131099823;
			
			// aapt resource value: 0x7f0600b1
			public const int prices_keyword_et = 2131099825;
			
			// aapt resource value: 0x7f0600b5
			public const int prices_local_competition_sp = 2131099829;
			
			// aapt resource value: 0x7f0600b9
			public const int prices_outlets_ll = 2131099833;
			
			// aapt resource value: 0x7f0600ae
			public const int prices_scrollview = 2131099822;
			
			// aapt resource value: 0x7f0600b6
			public const int prices_search_btn = 2131099830;
			
			// aapt resource value: 0x7f0600b2
			public const int prices_state_sp = 2131099826;
			
			// aapt resource value: 0x7f0600c4
			public const int pricesresult_family_tv = 2131099844;
			
			// aapt resource value: 0x7f0600c0
			public const int pricesresult_filter_apply_btn = 2131099840;
			
			// aapt resource value: 0x7f0600c1
			public const int pricesresult_filter_cancel_btn = 2131099841;
			
			// aapt resource value: 0x7f0600bd
			public const int pricesresult_filter_categories_fl = 2131099837;
			
			// aapt resource value: 0x7f0600bc
			public const int pricesresult_filter_ll = 2131099836;
			
			// aapt resource value: 0x7f0600bf
			public const int pricesresult_filter_search_et = 2131099839;
			
			// aapt resource value: 0x7f0600be
			public const int pricesresult_filter_search_fl = 2131099838;
			
			// aapt resource value: 0x7f0600ba
			public const int pricesresult_listview = 2131099834;
			
			// aapt resource value: 0x7f0600c2
			public const int pricesresult_name_tv = 2131099842;
			
			// aapt resource value: 0x7f0600bb
			public const int pricesresult_nothing_tv = 2131099835;
			
			// aapt resource value: 0x7f0600c3
			public const int pricesresult_optimum_price_tv = 2131099843;
			
			// aapt resource value: 0x7f0600c5
			public const int progressBar1 = 2131099845;
			
			// aapt resource value: 0x7f0600ca
			public const int promotioncell_category_iv = 2131099850;
			
			// aapt resource value: 0x7f0600cc
			public const int promotioncell_date_tv = 2131099852;
			
			// aapt resource value: 0x7f0600cd
			public const int promotioncell_desc_tv = 2131099853;
			
			// aapt resource value: 0x7f0600cb
			public const int promotioncell_name_tv = 2131099851;
			
			// aapt resource value: 0x7f0600c9
			public const int promotioncell_picture_iv = 2131099849;
			
			// aapt resource value: 0x7f0600ce
			public const int promotioncell_status_iv = 2131099854;
			
			// aapt resource value: 0x7f0600db
			public const int promotiondetail_accept_fl = 2131099867;
			
			// aapt resource value: 0x7f0600dd
			public const int promotiondetail_accept_no_btn = 2131099869;
			
			// aapt resource value: 0x7f0600dc
			public const int promotiondetail_accept_yes_btn = 2131099868;
			
			// aapt resource value: 0x7f0600d8
			public const int promotiondetail_addtocalendar_btn = 2131099864;
			
			// aapt resource value: 0x7f0600d1
			public const int promotiondetail_category_iv = 2131099857;
			
			// aapt resource value: 0x7f0600d3
			public const int promotiondetail_date_tv = 2131099859;
			
			// aapt resource value: 0x7f0600d4
			public const int promotiondetail_desc_tv = 2131099860;
			
			// aapt resource value: 0x7f0600d2
			public const int promotiondetail_name_tv = 2131099858;
			
			// aapt resource value: 0x7f0600de
			public const int promotiondetail_photos_fl = 2131099870;
			
			// aapt resource value: 0x7f0600df
			public const int promotiondetail_photosview_add_imgbtn = 2131099871;
			
			// aapt resource value: 0x7f0600e0
			public const int promotiondetail_photosview_addphoto_tv = 2131099872;
			
			// aapt resource value: 0x7f0600d0
			public const int promotiondetail_picture_iv = 2131099856;
			
			// aapt resource value: 0x7f0600d6
			public const int promotiondetail_sendfeedback_btn = 2131099862;
			
			// aapt resource value: 0x7f0600d7
			public const int promotiondetail_sendtomail_btn = 2131099863;
			
			// aapt resource value: 0x7f0600da
			public const int promotiondetail_status_iv = 2131099866;
			
			// aapt resource value: 0x7f0600d9
			public const int promotiondetail_status_tv = 2131099865;
			
			// aapt resource value: 0x7f0600cf
			public const int promotiondetail_sv = 2131099855;
			
			// aapt resource value: 0x7f0600d5
			public const int promotiondetail_viewdoc_btn = 2131099861;
			
			// aapt resource value: 0x7f0600e6
			public const int promotions_filter_apply_btn = 2131099878;
			
			// aapt resource value: 0x7f0600e7
			public const int promotions_filter_cancel_btn = 2131099879;
			
			// aapt resource value: 0x7f0600e3
			public const int promotions_filter_categories_fl = 2131099875;
			
			// aapt resource value: 0x7f0600e2
			public const int promotions_filter_ll = 2131099874;
			
			// aapt resource value: 0x7f0600e5
			public const int promotions_filter_search_et = 2131099877;
			
			// aapt resource value: 0x7f0600e4
			public const int promotions_filter_search_fl = 2131099876;
			
			// aapt resource value: 0x7f0600e1
			public const int promotions_listview = 2131099873;
			
			// aapt resource value: 0x7f0600c8
			public const int promotionview_btn = 2131099848;
			
			// aapt resource value: 0x7f0600c7
			public const int promotionview_name_tv = 2131099847;
			
			// aapt resource value: 0x7f0600c6
			public const int promotionview_picture_iv = 2131099846;
			
			// aapt resource value: 0x7f060038
			public const int radioview_desc_tv = 2131099704;
			
			// aapt resource value: 0x7f060037
			public const int radioview_picture_iv = 2131099703;
			
			// aapt resource value: 0x7f060036
			public const int radioview_radio_iv = 2131099702;
			
			// aapt resource value: 0x7f0600eb
			public const int selectplanogram_account_address_tv = 2131099883;
			
			// aapt resource value: 0x7f0600ec
			public const int selectplanogram_account_locationid_tv = 2131099884;
			
			// aapt resource value: 0x7f0600ea
			public const int selectplanogram_account_name_tv = 2131099882;
			
			// aapt resource value: 0x7f0600f3
			public const int selectplanogram_actions_fl = 2131099891;
			
			// aapt resource value: 0x7f0600f2
			public const int selectplanogram_answers_container_ll = 2131099890;
			
			// aapt resource value: 0x7f0600f4
			public const int selectplanogram_back_btn = 2131099892;
			
			// aapt resource value: 0x7f0600e9
			public const int selectplanogram_container_ll = 2131099881;
			
			// aapt resource value: 0x7f0600f5
			public const int selectplanogram_next_btn = 2131099893;
			
			// aapt resource value: 0x7f0600f0
			public const int selectplanogram_offer_name_tv = 2131099888;
			
			// aapt resource value: 0x7f0600ef
			public const int selectplanogram_offer_picture_iv = 2131099887;
			
			// aapt resource value: 0x7f0600f1
			public const int selectplanogram_offer_status_tv = 2131099889;
			
			// aapt resource value: 0x7f0600ee
			public const int selectplanogram_outlet_name_tv = 2131099886;
			
			// aapt resource value: 0x7f0600ed
			public const int selectplanogram_outlet_picture_iv = 2131099885;
			
			// aapt resource value: 0x7f0600fc
			public const int selectplanogram_planogram_back_btn = 2131099900;
			
			// aapt resource value: 0x7f0600fb
			public const int selectplanogram_planogram_details_tv = 2131099899;
			
			// aapt resource value: 0x7f0600f6
			public const int selectplanogram_planogram_ll = 2131099894;
			
			// aapt resource value: 0x7f0600f8
			public const int selectplanogram_planogram_name_tv = 2131099896;
			
			// aapt resource value: 0x7f0600fd
			public const int selectplanogram_planogram_next_btn = 2131099901;
			
			// aapt resource value: 0x7f0600fa
			public const int selectplanogram_planogram_picture_iv = 2131099898;
			
			// aapt resource value: 0x7f0600f7
			public const int selectplanogram_planogram_thumb_iv = 2131099895;
			
			// aapt resource value: 0x7f0600f9
			public const int selectplanogram_planogram_title_tv = 2131099897;
			
			// aapt resource value: 0x7f0600e8
			public const int selectplanogram_sv = 2131099880;
			
			// aapt resource value: 0x7f0600ff
			public const int splash_content = 2131099903;
			
			// aapt resource value: 0x7f0600fe
			public const int splash_view = 2131099902;
			
			// aapt resource value: 0x7f060100
			public const int viewdoc_webview = 2131099904;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account_View = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AccountDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Accounts = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Accounts_Cell = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AddOutlet = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int AddOutlet_View = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Dashboard = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Dashboard_Cell = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int DecisionTreeRadioView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int DecisionView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Feedback = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int FullImage = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int LeaveFeedback = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LookupAccount = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Main = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Me = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Offer_View = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int OfferCategoryView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int OfferDetail = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Outlet_View = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int OutletDetail_Cell = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int PlanogramCell = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Planograms = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Prices = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int PricesResult = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int PricesResultCell = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int progressdlg = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int PromotionCategoryView = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int PromotionCell = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int PromotionDetail = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Promotions = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int SelectPlanogram = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int Splash = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int ViewDoc = 2130903073;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int consumer_type_select_prompt = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
