// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Sodexo.Ipad2
{
	public partial class SDXTextField : UITextField
	{
		public SDXTextField (IntPtr handle) : base (handle)
		{
		}
	}
}
